XCODEBUILD=xcodebuild
OPTION_XCODEPROJ=-project Salmonia3.xcodeproj
OPTION_EXPORT_LOCALIZATIONS=-exportLocalizations 
OPTION_IMPORT_LOCALIZATIONS=-importLocalizations 
OPTION_EXPORT_LANG_EN=-exportLanguage en
OPTION_EXPORT_LANG_JA=-exportLanguage ja
PATH_LOCALIZATION_FILES_DIR=-localizationPath tmp/LocalizationFiles/
PATH_XCLOC_JA=$(PATH_LOCALIZATION_FILES_DIR)/ja.xcloc
PATH_XCLOC_EN=$(PATH_LOCALIZATION_FILES_DIR)/en.xcloc

export:
    $(XCODEBUILD) $(OPTION_EXPORT_LOCALIZATIONS) $(OPTION_EXPORT_LANG_EN) $(OPTION_XCODEPROJ) $(PATH_LOCALIZATION_FILES_DIR)
    $(XCODEBUILD) $(OPTION_EXPORT_LOCALIZATIONS) $(OPTION_EXPORT_LANG_JA) $(OPTION_XCODEPROJ) $(PATH_LOCALIZATION_FILES_DIR)

import:
    $(XCODEBUILD) $(OPTION_IMPORT_LOCALIZATIONS) $(OPTION_XCODEPROJ) $(PATH_XCLOC_EN)
    $(XCODEBUILD) $(OPTION_IMPORT_LOCALIZATIONS) $(OPTION_XCODEPROJ) $(PATH_XCLOC_JA)