extension WeaponType {
	var goldieSeeking: Double {
		switch self {
		case .randomGold:
			return 0
		case .randomGreen:
			return 0
		case .shooterShort:
			return 80
		case .shooterFirst:
			return 65
		case .shooterPrecision:
			return 65
		case .shooterBlaze:
			return 65
		case .shooterNormal:
			return 65
		case .shooterGravity:
			return 65
		case .shooterQuickMiddle:
			return 65
		case .shooterExpert:
			return 65
		case .shooterHeavy:
			return 80
		case .shooterLong:
			return 50
		case .shooterBlasterShort:
			return 65
		case .shooterBlasterMiddle:
			return 50
		case .shooterBlasterLong:
			return 20
		case .shooterBlasterLightShort:
			return 50
		case .shooterBlasterLight:
			return 50
		case .shooterBlasterLightLong:
			return 35
		case .shooterTripleQuick:
			return 80
		case .shooterTripleMiddle:
			return 65
		case .shooterFlash:
			return 65
		case .rollerCompact:
			return 50
		case .rollerNormal:
			return 65
		case .rollerHeavy:
			return 120
		case .rollerHunter:
			return 80
		case .rollerBrushMini:
			return 57
		case .rollerBrushNormal:
			return 57
		case .chargerQuick:
			return 80
		case .chargerNormal:
			return 65
		case .chargerNormalScope:
			return 65
		case .chargerLong:
			return 80
		case .chargerLongScope:
			return 80
		case .chargerLight:
			return 80
		case .chargerKeeper:
			return 50
		case .slosherStrong:
			return 20
		case .slosherDiffusion:
			return 50
		case .slosherLauncher:
			return 50
		case .slosherBathtub:
			return 90
		case .slosherWashtub:
			return 35
		case .spinnerQuick:
			return 80
		case .spinnerStandard:
			return 80
		case .spinnerHyper:
			return 90
		case .spinnerDownpour:
			return 90
		case .spinnerSerein:
			return 80
		case .twinsShort:
			return 80
		case .twinsNormal:
			return 80
		case .twinsGallon:
			return 80
		case .twinsDual:
			return 65
		case .twinsStepper:
			return 65
		case .umbrellaNormal:
			return 65
		case .umbrellaWide:
			return 50
		case .umbrellaCompact:
			return 50
		case .shooterBlasterBurst:
			return 65
		case .umbrellaAutoAssault:
			return 50
		case .chargerSpark:
			return 90
		case .slosherVase:
			return 50
		default:
			return 0
		}
	}

}

