extension WeaponType {
	var internal: Double {
		switch self {
		case .randomGold:
			return randomGold
		case .randomGreen:
			return randomGreen
		case .shooterShort:
			return shooterShort
		case .shooterFirst:
			return shooterFirst
		case .shooterPrecision:
			return shooterPrecision
		case .shooterBlaze:
			return shooterBlaze
		case .shooterNormal:
			return shooterNormal
		case .shooterGravity:
			return shooterGravity
		case .shooterQuickMiddle:
			return shooterQuickMiddle
		case .shooterExpert:
			return shooterExpert
		case .shooterHeavy:
			return shooterHeavy
		case .shooterLong:
			return shooterLong
		case .shooterBlasterShort:
			return shooterBlasterShort
		case .shooterBlasterMiddle:
			return shooterBlasterMiddle
		case .shooterBlasterLong:
			return shooterBlasterLong
		case .shooterBlasterLightShort:
			return shooterBlasterLightShort
		case .shooterBlasterLight:
			return shooterBlasterLight
		case .shooterBlasterLightLong:
			return shooterBlasterLightLong
		case .shooterTripleQuick:
			return shooterTripleQuick
		case .shooterTripleMiddle:
			return shooterTripleMiddle
		case .shooterFlash:
			return shooterFlash
		case .rollerCompact:
			return rollerCompact
		case .rollerNormal:
			return rollerNormal
		case .rollerHeavy:
			return rollerHeavy
		case .rollerHunter:
			return rollerHunter
		case .rollerBrushMini:
			return rollerBrushMini
		case .rollerBrushNormal:
			return rollerBrushNormal
		case .chargerQuick:
			return chargerQuick
		case .chargerNormal:
			return chargerNormal
		case .chargerNormalScope:
			return chargerNormalScope
		case .chargerLong:
			return chargerLong
		case .chargerLongScope:
			return chargerLongScope
		case .chargerLight:
			return chargerLight
		case .chargerKeeper:
			return chargerKeeper
		case .slosherStrong:
			return slosherStrong
		case .slosherDiffusion:
			return slosherDiffusion
		case .slosherLauncher:
			return slosherLauncher
		case .slosherBathtub:
			return slosherBathtub
		case .slosherWashtub:
			return slosherWashtub
		case .spinnerQuick:
			return spinnerQuick
		case .spinnerStandard:
			return spinnerStandard
		case .spinnerHyper:
			return spinnerHyper
		case .spinnerDownpour:
			return spinnerDownpour
		case .spinnerSerein:
			return spinnerSerein
		case .twinsShort:
			return twinsShort
		case .twinsNormal:
			return twinsNormal
		case .twinsGallon:
			return twinsGallon
		case .twinsDual:
			return twinsDual
		case .twinsStepper:
			return twinsStepper
		case .umbrellaNormal:
			return umbrellaNormal
		case .umbrellaWide:
			return umbrellaWide
		case .umbrellaCompact:
			return umbrellaCompact
		case .shooterBlasterBurst:
			return shooterBlasterBurst
		case .umbrellaAutoAssault:
			return umbrellaAutoAssault
		case .chargerSpark:
			return chargerSpark
		case .slosherVase:
			return slosherVase
		default:
			return 0
		}
	}

}

