extension WeaponType {
	var rank: Double {
		switch self {
		case .randomGold:
			return 0
		case .randomGreen:
			return 0
		case .shooterShort:
			return 83
		case .shooterFirst:
			return 57
		case .shooterPrecision:
			return 62
		case .shooterBlaze:
			return 57
		case .shooterNormal:
			return 66
		case .shooterGravity:
			return 67
		case .shooterQuickMiddle:
			return 60
		case .shooterExpert:
			return 50
		case .shooterHeavy:
			return 72
		case .shooterLong:
			return 48
		case .shooterBlasterShort:
			return 78
		case .shooterBlasterMiddle:
			return 58
		case .shooterBlasterLong:
			return 48
		case .shooterBlasterLightShort:
			return 50
		case .shooterBlasterLight:
			return 58
		case .shooterBlasterLightLong:
			return 41
		case .shooterTripleQuick:
			return 72
		case .shooterTripleMiddle:
			return 46
		case .shooterFlash:
			return 46
		case .rollerCompact:
			return 52
		case .rollerNormal:
			return 52
		case .rollerHeavy:
			return 46
		case .rollerHunter:
			return 57
		case .rollerBrushMini:
			return 37
		case .rollerBrushNormal:
			return 52
		case .chargerQuick:
			return 76
		case .chargerNormal:
			return 62
		case .chargerNormalScope:
			return 58
		case .chargerLong:
			return 54
		case .chargerLongScope:
			return 50
		case .chargerLight:
			return 70
		case .chargerKeeper:
			return 40
		case .slosherStrong:
			return 46
		case .slosherDiffusion:
			return 48
		case .slosherLauncher:
			return 42
		case .slosherBathtub:
			return 84
		case .slosherWashtub:
			return 52
		case .spinnerQuick:
			return 76
		case .spinnerStandard:
			return 72
		case .spinnerHyper:
			return 48
		case .spinnerDownpour:
			return 88
		case .spinnerSerein:
			return 72
		case .twinsShort:
			return 92
		case .twinsNormal:
			return 78
		case .twinsGallon:
			return 64
		case .twinsDual:
			return 48
		case .twinsStepper:
			return 58
		case .umbrellaNormal:
			return 85
		case .umbrellaWide:
			return 53
		case .umbrellaCompact:
			return 46
		case .shooterBlasterBurst:
			return 80
		case .umbrellaAutoAssault:
			return 53
		case .chargerSpark:
			return 120
		case .slosherVase:
			return 120
		default:
			return 0
		}
	}

}

