//
//  Deviation.swift
//  Salmonia3
//
//  Created by devonly on 2022/02/24.
//

import Foundation
import SplatNet2

extension WeaponType {
    /// 射程
    var range: Double {
        switch self {
        case .shooterShort:
            return 79.65
        case .shooterFirst:
            return 107.77
        case .shooterPrecision:
            return 112.45
        case .shooterBlaze:
            return 107.77
        case .shooterNormal:
            return 121.82
        case .shooterGravity:
            return 131.19
        case .shooterQuickMiddle:
            return 121.82
        case .shooterExpert:
            return 163.99
        case .shooterHeavy:
            return 173.36
        case .shooterLong:
            return 215.53
        case .shooterBlasterShort:
            return 74.97
        case .shooterBlasterMiddle:
            return 98.4
        case .shooterBlasterLong:
            return 131.19
        case .shooterBlasterLightShort:
            return 89.02
        case .shooterBlasterLight:
            return 145.25
        case .shooterBlasterLightLong:
            return 168.68
        case .shooterTripleQuick:
            return 145.25
        case .shooterTripleMiddle:
            return 163.99
        case .shooterFlash:
            return 192.1
        case .rollerCompact:
            return 74.97
        case .rollerNormal:
            return 117.14
        case .rollerHeavy:
            return 149.94
        case .rollerHunter:
            return 103.08
        case .rollerBrushMini:
            return 74.97
        case .rollerBrushNormal:
            return 98.4
        case .chargerQuick:
            return 178.05
        case .chargerNormal:
            return 243.65
        case .chargerNormalScope:
            return 262.39
        case .chargerLong:
            return 290.5
        case .chargerLongScope:
            return 309.24
        case .chargerLight:
            return 201.48
        case .chargerKeeper:
            return 196.79
        case .slosherStrong:
            return 140.56
        case .slosherDiffusion:
            return 112.45
        case .slosherLauncher:
            return 140.56
        case .slosherBathtub:
            return 257.7
        case .slosherWashtub:
            return 196.79
        case .spinnerQuick:
            return 149.94
        case .spinnerStandard:
            return 210.85
        case .spinnerHyper:
            return 243.65
        case .spinnerDownpour:
            return 112.45
        case .spinnerSerein:
            return 178.05
        case .twinsShort:
            return 93.71
        case .twinsNormal:
            return 121.82
        case .twinsGallon:
            return 145.25
        case .twinsDual:
            return 163.99
        case .twinsStepper:
            return 135.88
        case .umbrellaNormal:
            return 121.82
        case .umbrellaWide:
            return 154.62
        case .umbrellaCompact:
            return 126.51
        case .shooterBlasterBurst:
            return 89.02
        case .umbrellaAutoAssault:
            return 121.82
        case .chargerSpark:
            return 290.5
        case .slosherVase:
            return 215.53
        default:
            return 0
        }
    }
    
    /// ダメージ
    var damage: Double {
        switch self {
        case .shooterShort:
            return 450
        case .shooterFirst:
            return 280
        case .shooterPrecision:
            return 280
        case .shooterBlaze:
            return 240
        case .shooterNormal:
            return 350
        case .shooterGravity:
            return 520
        case .shooterQuickMiddle:
            return 280
        case .shooterExpert:
            return 450
        case .shooterHeavy:
            return 850
        case .shooterLong:
            return 350
        case .shooterBlasterShort:
            return 2000
        case .shooterBlasterMiddle:
            return 2000
        case .shooterBlasterLong:
            return 2000
        case .shooterBlasterLightShort:
            return 850
        case .shooterBlasterLight:
            return 1400
        case .shooterBlasterLightLong:
            return 1400
        case .shooterTripleQuick:
            return 400
        case .shooterTripleMiddle:
            return 600
        case .shooterFlash:
            return 450
        case .rollerCompact:
            return 1600
        case .rollerNormal:
            return 2000
        case .rollerHeavy:
            return 2000
        case .rollerHunter:
            return 2000
        case .rollerBrushMini:
            return 300
        case .rollerBrushNormal:
            return 600
        case .chargerQuick:
            return 3000
        case .chargerNormal:
            return 3000
        case .chargerNormalScope:
            return 3000
        case .chargerLong:
            return 6000
        case .chargerLongScope:
            return 6000
        case .chargerLight:
            return 1600
        case .chargerKeeper:
            return 3000
        case .slosherStrong:
            return 1000
        case .slosherDiffusion:
            return 1000
        case .slosherLauncher:
            return 1500
        case .slosherBathtub:
            return 600
        case .slosherWashtub:
            return 1250
        case .spinnerQuick:
            return 350
        case .spinnerStandard:
            return 350
        case .spinnerHyper:
            return 600
        case .spinnerDownpour:
            return 350
        case .spinnerSerein:
            return 350
        case .twinsShort:
            return 450
        case .twinsNormal:
            return 300
        case .twinsGallon:
            return 450
        case .twinsDual:
            return 300
        case .twinsStepper:
            return 300
        case .umbrellaNormal:
            return 360
        case .umbrellaWide:
            return 350
        case .umbrellaCompact:
            return 300
        case .shooterBlasterBurst:
            return 500
        case .umbrellaAutoAssault:
            return 150
        case .chargerSpark:
            return 2000
        case .slosherVase:
            return 3600
        default:
            return 0
        }
    }
    
    /// インク消費
    var inkConsume: Double {
        switch self {
        case .shooterShort:
            return 0.008
        case .shooterFirst:
            return 0.005
        case .shooterPrecision:
            return 0.008
        case .shooterBlaze:
            return 0.0055
        case .shooterNormal:
            return 0.01
        case .shooterGravity:
            return 0.013
        case .shooterQuickMiddle:
            return 0.0085
        case .shooterExpert:
            return 0.02
        case .shooterHeavy:
            return 0.025
        case .shooterLong:
            return 0.016
        case .shooterBlasterShort:
            return 0.04
        case .shooterBlasterMiddle:
            return 0.048
        case .shooterBlasterLong:
            return 0.055
        case .shooterBlasterLightShort:
            return 0.032
        case .shooterBlasterLight:
            return 0.045
        case .shooterBlasterLightLong:
            return 0.065
        case .shooterTripleQuick:
            return 0.01
        case .shooterTripleMiddle:
            return 0.018
        case .shooterFlash:
            return 0.022
        case .rollerCompact:
            return 0.035
        case .rollerNormal:
            return 0.06
        case .rollerHeavy:
            return 0.2
        case .rollerHunter:
            return 0.06
        case .rollerBrushMini:
            return 0.02
        case .rollerBrushNormal:
            return 0.032
        case .chargerQuick:
            return 0.084
        case .chargerNormal:
            return 0.18
        case .chargerNormalScope:
            return 0.18
        case .chargerLong:
            return 0.25
        case .chargerLongScope:
            return 0.25
        case .chargerLight:
            return 0.04
        case .chargerKeeper:
            return 0.12
        case .slosherStrong:
            return 0.055
        case .slosherDiffusion:
            return 0.045
        case .slosherLauncher:
            return 0.055
        case .slosherBathtub:
            return 0.06
        case .slosherWashtub:
            return 0.09
        case .spinnerQuick:
            return 0.00789
        case .spinnerStandard:
            return 0.00608
        case .spinnerHyper:
            return 0.00574
        case .spinnerDownpour:
            return 0.005
        case .spinnerSerein:
            return 0.00519
        case .twinsShort:
            return 0.00663
        case .twinsNormal:
            return 0.008
        case .twinsGallon:
            return 0.014
        case .twinsDual:
            return 0.008
        case .twinsStepper:
            return 0.008
        case .umbrellaNormal:
            return 0.025
        case .umbrellaWide:
            return 0.05
        case .umbrellaCompact:
            return 0.03
        case .shooterBlasterBurst:
            return 0.03
        case .umbrellaAutoAssault:
            return 0.02
        case .chargerSpark:
            return 0.13
        case .slosherVase:
            return 0.25
        default:
            return 1
        }
    }
    
    /// 1フレームあたりのダメージ
    var damagePerFrame: Double {
        damage / frame
    }
    
    /// 射撃継続可能時間
    var continueTime: Double {
        1 / (inkConsume / frame)
    }
    
    /// カバーできるエリア内の火力
    var fieldDamagePerFrame: Double {
        // 射程はデュアル以上はサーモンランでは不要と考える
        min(163.99, range) * damagePerFrame * continueTime
    }
    
    /// インク全消費時の総合ダメージ
    var totalDamage: Double {
        switch self {
        case .shooterShort:
            return 56250
        case .shooterFirst:
            return 56000
        case .shooterPrecision:
            return 35000
        case .shooterBlaze:
            return 43200
        case .shooterNormal:
            return 35000
        case .shooterGravity:
            return 39520
        case .shooterQuickMiddle:
            return 32760
        case .shooterExpert:
            return 22500
        case .shooterHeavy:
            return 34000
        case .shooterLong:
            return 21700
        case .shooterBlasterShort:
            return 50000
        case .shooterBlasterMiddle:
            return 40000
        case .shooterBlasterLong:
            return 36000
        case .shooterBlasterLightShort:
            return 26350
        case .shooterBlasterLight:
            return 30800
        case .shooterBlasterLightLong:
            return 21000
        case .shooterTripleQuick:
            return 40000
        case .shooterTripleMiddle:
            return 33000
        case .shooterFlash:
            return 18000
        case .rollerCompact:
            return 44800
        case .rollerNormal:
            return 32000
        case .rollerHeavy:
            return 10000
        case .rollerHunter:
            return 32000
        case .rollerBrushMini:
            return 15000
        case .rollerBrushNormal:
            return 18600
        case .chargerQuick:
            return 35710
        case .chargerNormal:
            return 16670
        case .chargerNormalScope:
            return 16670
        case .chargerLong:
            return 24000
        case .chargerLongScope:
            return 24000
        case .chargerLight:
            return 40000
        case .chargerKeeper:
            return 25000
        case .slosherStrong:
            return 18000
        case .slosherDiffusion:
            return 22000
        case .slosherLauncher:
            return 27000
        case .slosherBathtub:
            return 38400
        case .slosherWashtub:
            return 22000
        case .spinnerQuick:
            return 44330
        case .spinnerStandard:
            return 57550
        case .spinnerHyper:
            return 104570
        case .spinnerDownpour:
            return 70000
        case .spinnerSerein:
            return 67500
        case .twinsShort:
            return 67500
        case .twinsNormal:
            return 37500
        case .twinsGallon:
            return 31950
        case .twinsDual:
            return 37500
        case .twinsStepper:
            return 37500
        case .umbrellaNormal:
            return 72000
        case .umbrellaWide:
            return 49000
        case .umbrellaCompact:
            return 39600
        case .shooterBlasterBurst:
            return 21000
        case .umbrellaAutoAssault:
            return 28200
        case .chargerSpark:
            return 14000
        case .slosherVase:
            return 14400
        default:
            return 0
        }
    }
    
    /// 一発あたりの射撃要フレーム数
    var frame: Double {
        switch self {
        case .shooterShort:
            return 5
        case .shooterFirst:
            return 5
        case .shooterPrecision:
            return 5
        case .shooterBlaze:
            return 4
        case .shooterNormal:
            return 6
        case .shooterGravity:
            return 9
        case .shooterQuickMiddle:
            return 5
        case .shooterExpert:
            return 8
        case .shooterHeavy:
            return 12
        case .shooterLong:
            return 8
        case .shooterBlasterShort:
            return 40
        case .shooterBlasterMiddle:
            return 50
        case .shooterBlasterLong:
            return 60
        case .shooterBlasterLightShort:
            return 20
        case .shooterBlasterLight:
            return 35
        case .shooterBlasterLightLong:
            return 40
        case .shooterTripleQuick:
            return 4
        case .shooterTripleMiddle:
            return 5
        case .shooterFlash:
            return 8
        case .rollerCompact:
            return 31
        case .rollerNormal:
            return 42
        case .rollerHeavy:
            return 66
        case .rollerHunter:
            return 40
        case .rollerBrushMini:
            return 7
        case .rollerBrushNormal:
            return 11
        case .chargerQuick:
            return 45
        case .chargerNormal:
            return 60
        case .chargerNormalScope:
            return 60
        case .chargerLong:
            return 92
        case .chargerLongScope:
            return 92
        case .chargerLight:
            return 20
        case .chargerKeeper:
            return 75
        case .slosherStrong:
            return 30
        case .slosherDiffusion:
            return 24
        case .slosherLauncher:
            return 34
        case .slosherBathtub:
            return 32
        case .slosherWashtub:
            return 55
        case .spinnerQuick:
            return 6
        case .spinnerStandard:
            return 6
        case .spinnerHyper:
            return 6
        case .spinnerDownpour:
            return 4
        case .spinnerSerein:
            return 7
        case .twinsShort:
            return 5
        case .twinsNormal:
            return 5
        case .twinsGallon:
            return 9
        case .twinsDual:
            return 6
        case .twinsStepper:
            return 6
        case .umbrellaNormal:
            return 29
        case .umbrellaWide:
            return 51
        case .umbrellaCompact:
            return 26
        case .shooterBlasterBurst:
            return 9
        case .umbrellaAutoAssault:
            return 12
        case .chargerSpark:
            return 10
        case .slosherVase:
            return 40
        default:
            return 1
        }
    }
}
