import Foundation

class LocalizableStrings {

    enum Key: String {
        case AUTHORIZED_WITH_BIOMETRICS
        case AUTHORIZED_WITH_PASSCODE
        case ALERT_ERROR
        case BOSS_DEFEATED
        case BTN_CANCEL
        case BTN_CONFIRM
        case BTN_DISMISS
        case BTN_MIGRATE
        case BTN_SIGN_IN
        case BTN_SIGN_OUT
        case BTN_SIGN_UP
        case DISABLED
        case ENABLED
        case ERASE_DATA
        case ERROR_BADREQUEST
        case ERROR_EMPTY
        case ERROR_EXPIRED
        case ERROR_FORBIDDEN
        case ERROR_INVALID
        case ERROR_METHOD
        case ERROR_NODATA
        case ERROR_REQUESTS
        case ERROR_UNAUTHORIZED
        case ERROR_UNAVAILABLE
        case ERROR_UNKNOWN
        case ERROR_UPGRADE
        case FEATURE_FREE_01
        case FEATURE_FREE_01_DESC
        case FEATURE_FREE_02
        case FEATURE_FREE_02_DESC
        case FEATURE_FREE_03
        case FEATURE_FREE_03_DESC
        case FEATURE_PAID_01
        case FEATURE_PAID_01_DESC
        case FEATURE_PAID_02
        case FEATURE_PAID_02_DESC
        case FEATURE_PAID_03
        case FEATURE_PAID_03_DESC
        case GOLDEN_EGGS
        case HEADER_APPEARANCE
        case HEADER_APPLICATION
        case HEADER_DEVICE
        case HEADER_OVERVIEW
        case HEADER_PRODUCT
        case HEADER_SALMONSTATS
        case HEADER_SCHEDULE
        case HEADER_STAGE_RECORD
        case HEADER_STATS_AVG
        case HEADER_STATS_MAX
        case HEADER_USERINFO
        case LOG_DOWNLOAD
        case LOG_UPLOADING
        case PRODUCT_MULTI_ACCOUNT
        case RESIGN_IN
        case RESULTS
        case RESULT_CLEAR
        case RESULT_CLEAR_RATIO
        case RESULT_CLEAR_WAVE
        case RESULT_CREW_GRADE
        case RESULT_DEAD_COUNT
        case RESULT_DEFEAT
        case RESULT_DEFEATED
        case RESULT_EGG_COUNT
        case RESULT_EVALUATION
        case RESULT_GOLDEN_EGGS
        case RESULT_GRADE_POINT
        case RESULT_HAZARD_LEVEL_MAX
        case RESULT_HELP_COUNT
        case RESULT_JOB_NUM
        case RESULT_KILL_COUNT
        case RESULT_MAX_GRADE
        case RESULT_PLAYER
        case RESULT_POWER_EGGS
        case RESULT_RATIO_GOLDEN_EGGS
        case RESULT_RATIO_POWER_EGGS
        case RESULT_SALMONIDS
        case RESULT_SALMON_RATE
        case RESULT_TEAM_GOLDEN_EGGS
        case RESULT_TEAM_POWER_EGGS
        case SETTING_API_VERSION
        case SETTING_APP_VERSION
        case SETTING_DARKMODE
        case SETTING_DETAIL
        case SETTING_DEVICE
        case SETTING_ERASE_DATA
        case SETTING_FREE_PRODUCT
        case SETTING_IMPORT_RESULT
        case SETTING_PAID_PRODUCT
        case SETTING_PRIVACY
        case SETTING_RESULTS
        case SETTING_RE_SIGN_IN
        case SETTING_SYSTEM
        case SETTING_UPDATE_NAME
        case SETTING_UPLOAD
        case SETTING_LOADING_TYPE
        case SETTING_LOG_SEND
        case SETTING_IMPORT_NUM
        case SHIFT_SCHEDULE
        case SUPPLIED_WEAPONS
        case TEXT_CONFIRM
        case TEXT_ERASE_DATA
        case TEXT_RE_SIGN_IN
        case TEXT_SALMONIA
        case TEXT_SALMONSTATS
        case TEXT_TUTORIAL_SALMONSTATS
        case TEXT_WELCOME_SALMONSTATS
        case TEXT_WELCOME_SPLATNET2
        case TITLE_FREE_PRODUCT
        case TITLE_LOGGING_THREAD
        case TITLE_LOGIN
        case TITLE_PAID_PRODUCT
        case TITLE_RESULT
        case TITLE_RESULT_COLLECTION
        case TITLE_RESULT_DETAIL
        case TITLE_SALMONIA
        case TITLE_SETTINGS
        case TITLE_SHIFT_SCHEDULE
        case TITLE_SHIFT_STATS
        case TITLE_WAVE_ANALYSIS
        case TITLE_WEAPON_ANALYSIS
        case SALMON_RUN_RECORDS
        case SALMON_STATS
        case LANPLAY_RECORDS
    }

}
