import Foundation

class LocalizableStrings {

    enum Key: String {
        case ALERT_ERROR
        case ALERT_SIGN_IN
        case AUTHORIZED_WITH_BIOMETRICS
        case AUTHORIZED_WITH_PASSCODE
        case BOSS_DEFEATED
        case BTN_ADD_ACCOUNT
        case BTN_CANCEL
        case BTN_CONFIRM
        case BTN_DISMISS
        case BTN_MIGRATE
        case BTN_SIGN_IN
        case BTN_SIGN_OUT
        case BTN_SIGN_UP
        case DISABLED
        case ENABLED
        case ERASE_DATA
        case ERROR_BADREQUEST
        case ERROR_EMPTY
        case ERROR_EXPIRED
        case ERROR_FORBIDDEN
        case ERROR_INVALID
        case ERROR_METHOD
        case ERROR_NODATA
        case ERROR_REQUESTS
        case ERROR_UNAUTHORIZED
        case ERROR_UNAVAILABLE
        case ERROR_UNKNOWN
        case ERROR_UPGRADE
        case FEATURE_FREE_01
        case FEATURE_FREE_01_DESC
        case FEATURE_FREE_02
        case FEATURE_FREE_02_DESC
        case FEATURE_FREE_03
        case FEATURE_FREE_03_DESC
        case FEATURE_FREE_04
        case FEATURE_FREE_04_DESC
        case FEATURE_FREE_05
        case FEATURE_FREE_05_DESC
        case FEATURE_PAID_01
        case FEATURE_PAID_01_DESC
        case FEATURE_PAID_02
        case FEATURE_PAID_02_DESC
        case FEATURE_PAID_03
        case FEATURE_PAID_03_DESC
        case FEATURE_RESET_DESC
        case FEATURE_RESTORE_DESC
        case FOOTER_ERASE_DATA
        case FOOTER_SALMONSTATS
        case FOOTER_SIGN_OUT
        case FOOTER_SPLATNET2
        case GOLDEN_EGGS
        case HEADER_APPEARANCE
        case HEADER_APPLICATION
        case HEADER_DATA
        case HEADER_DEVICE
        case HEADER_OVERVIEW
        case HEADER_PRIVACY
        case HEADER_PRODUCT
        case HEADER_SALMONSTATS
        case HEADER_SCHEDULE
        case HEADER_SPECIAL_WEAPON
        case HEADER_STAGE_RECORD
        case HEADER_STATS_AVG
        case HEADER_STATS_MAX
        case HEADER_USERINFO
        case HELP_GET_RESULT
        case HELP_IMPORT_RESULT
        case LANPLAY_RECORDS
        case LOCK
        case LOG_DOWNLOAD
        case LOG_UPLOADING
        case NIGHT_WAVE
        case NO_NIGHT_WAVE
        case PAID
        case PLAY_VIDEO
        case PRODUCT_MULTI_ACCOUNT
        case PURCHASE
        case PURCHASED
        case RESET
        case RESIGN_IN
        case RESTORE
        case RESTORE_MESSAGE
        case RESULTS
        case RESULT_CLEAR
        case RESULT_CLEAR_RATIO
        case RESULT_CLEAR_WAVE
        case RESULT_CREW_AVG_NUM
        case RESULT_CREW_GRADE
        case RESULT_DEAD_COUNT
        case RESULT_DEFEAT
        case RESULT_DEFEATED
        case RESULT_EGG_COUNT
        case RESULT_EVALUATION
        case RESULT_GOLDEN_EGGS
        case RESULT_GRADE_POINT
        case RESULT_HAZARD_LEVEL_MAX
        case RESULT_HELP_COUNT
        case RESULT_JOB_NUM
        case RESULT_KILL_COUNT
        case RESULT_MAX_GOLDEN_EGGS
        case RESULT_MAX_GOLDEN_EGGS_NONIGHT
        case RESULT_MAX_GRADE
        case RESULT_MAX_GRADE_NUM
        case RESULT_MIN_MAX_GRADE
        case RESULT_PLAYER
        case RESULT_POWER_EGGS
        case RESULT_RATIO_GOLDEN_EGGS
        case RESULT_RATIO_POWER_EGGS
        case RESULT_SALMONIDS
        case RESULT_SALMON_RATE
        case RESULT_TEAM_GOLDEN_EGGS
        case RESULT_TEAM_POWER_EGGS
        case SALMON_RUN_RECORDS
        case SALMON_STATS
        case SETTING_ACCOUNT
        case SETTING_ADD_ACCOUNT
        case SETTING_API_VERSION
        case SETTING_APP_VERSION
        case SETTING_DARKMODE
        case SETTING_DETAIL
        case SETTING_DEVICE
        case SETTING_ENABLE_IMPORT
        case SETTING_ERASE_DATA
        case SETTING_FREE_PRODUCT
        case SETTING_GENERAL
        case SETTING_HELP
        case SETTING_IMPORTANT
        case SETTING_IMPORT_NUM
        case SETTING_IMPORT_RESULT
        case SETTING_LISTSTYLE
        case SETTING_LOADING_TYPE
        case SETTING_LOGOUT_ALL
        case SETTING_LOG_SEND
        case SETTING_PAID_PRODUCT
        case SETTING_PRIVACY
        case SETTING_RESULTS
        case SETTING_RESULTSTYLE
        case SETTING_RE_SIGN_IN
        case SETTING_SIGN_OUT
        case SETTING_SPLATNET2
        case SETTING_SYSTEM
        case SETTING_UPDATE_NAME
        case SETTING_UPLOAD
        case SHIFT_SCHEDULE
        case SUPPLIED_WEAPONS
        case TEXT_ADD_ACCOUNT
        case TEXT_ALL_LOGOUT
        case TEXT_CHOOSE_STYLE
        case TEXT_CONFIRM
        case TEXT_ERASE_DATA
        case TEXT_IMPORT
        case TEXT_RE_SIGN_IN
        case TEXT_SALMONIA
        case TEXT_SALMONSTATS
        case TEXT_SIGN_IN
        case TEXT_SIGN_OUT
        case TEXT_TUTORIAL
        case TEXT_TUTORIAL_SALMONSTATS
        case TEXT_WELCOME_SALMONSTATS
        case TEXT_WELCOME_SPLATNET2
        case TITLE_USER
        case TITLE_FREE_PRODUCT
        case TITLE_HELP
        case TITLE_LOGGING_THREAD
        case TITLE_LOGIN
        case TITLE_PAID_PRODUCT
        case TITLE_PLAYER_COLLECTION
        case TITLE_RESULT
        case TITLE_RESULT_COLLECTION
        case TITLE_RESULT_DETAIL
        case TITLE_SALMONIA
        case TITLE_SETTINGS
        case TITLE_SHIFT_SCHEDULE
        case TITLE_SHIFT_STATS
        case TITLE_TUTORIAL
        case TITLE_WAVE_ANALYSIS
        case TITLE_WAVE_COLLECTION
        case TITLE_WEAPON_ANALYSIS
        case FAILURE_WAVE_1
        case FAILURE_WAVE_2
        case FAILURE_WAVE_3
        case FAILURE_WIPE_OUT
        case FAILURE_TIME_LIMIT
        case HEADER_FAILURE_REASON
        case HEADER_FAILURE_WAVE
        case CLEAR_WAVE
        case TITLE_RECORD
        case TITLE_COLLECTION
        case SETTING_SALMONSTATS
        case TITLE_SALMONSTATS
        case LAST_MATCHED_TIME
        case TEXT_PURCHASED
        case TEXT_MAIN_WEAPON
        case TEXT_SUPPLIED_WEAPON
        case TEXT_NOT_SUPPLIED_WEAPON
        case TEXT_SPECIAL_WEAPON
//        case HEADER_STAGE_RECORD
//        case HEADER_MAXGRADE
//        case HEADER_999COUNTS
//        case HEADER_MIN999COUNTS
    }

}
